package shared.net;

public enum ActionType {
    // Thuoc
    GET_ALL_THUOC, GET_THUOC_BY_MA, ADD_THUOC, UPDATE_THUOC, SEARCH_THUOC, GET_ALL_TEN_THUOC, GET_ALL_ACTIVE_THUOC, UPDATE_TRANG_THAI_THUOC, GET_NEXT_MA_THUOC,
    SEARCH_THUOC_FOR_SALE, UPDATE_THUOC_QUANTITY,
    
    // KhachHang
    GET_ALL_KHACH_HANG, ADD_KHACH_HANG, UPDATE_KHACH_HANG, DELETE_KHACH_HANG, SEARCH_KHACH_HANG, GET_KHACH_HANG_BY_MA, GET_KHACH_HANG_BY_SDT, GET_NEXT_MA_KHACH_HANG,
    
    // NhanVien
    GET_ALL_NHAN_VIEN, ADD_NHAN_VIEN, UPDATE_NHAN_VIEN, DELETE_NHAN_VIEN, SEARCH_NHAN_VIEN, GET_NHAN_VIEN_BY_MA, GET_NHAN_VIEN_BY_MA_TK, GET_NEXT_MA_NHAN_VIEN, GENERATE_NEW_MA_NV_FROM_TABLE, CHECK_SDT_TON_TAI, CHECK_SDT_TON_TAI_NV,
    
    // HoaDon
    GET_ALL_HOA_DON, ADD_HOA_DON, GET_HOA_DON_BY_MA, GET_DETAILS_BY_HOA_DON, GET_NEXT_MA_HOA_DON,
    GET_ALL_HOA_DON_CHI_TIET_FOR_TABLE, SEARCH_HOA_DON_CHI_TIET, GET_DS_THUOC_BY_HOA_DON, ADD_PHIEU_DOI_TRA, ADD_CT_PHIEU_DOI_TRA, GET_NEXT_MA_PHIEU_DOI_TRA,
    
    // TaiKhoan
    GET_ALL_TAI_KHOAN, ADD_TAI_KHOAN, UPDATE_TAI_KHOAN, DELETE_TAI_KHOAN, GET_TAI_KHOAN_BY_MA, GET_NEXT_MA_TAI_KHOAN,
    LOGIN, UPDATE_PASSWORD, GET_TAI_KHOAN_BY_USERNAME,
    
    // PhieuCho
    GET_ALL_PHIEU_CHO, ADD_PHIEU_CHO, DELETE_PHIEU_CHO, DELETE_ALL_PHIEU_CHO, GET_NEXT_MA_PHIEU_CHO, GET_DETAILS_BY_PHIEU_CHO, GET_PHIEU_CHO_BY_MA,
    
    // PhieuDatHang
    GET_ALL_PHIEU_DAT_HANG, ADD_PHIEU_DAT_HANG, UPDATE_PHIEU_DAT_HANG, CANCEL_PHIEU_DAT_HANG, GET_PHIEU_DAT_HANG_BY_MA, GET_DETAILS_BY_PHIEU_DAT_HANG, GET_NEXT_MA_PHIEU_DAT_HANG,
    
    // Utilities/Others
    GET_ALL_NHA_CUNG_CAP, GET_NHA_CUNG_CAP_BY_MA, GET_NHA_CUNG_CAP_BY_TEN, ADD_NHA_CUNG_CAP, UPDATE_NHA_CUNG_CAP, GET_NEXT_MA_NHA_CUNG_CAP,
    GET_ALL_KE_THUOC, GET_KE_THUOC_BY_MA, GET_KE_THUOC_BY_TEN,
    GET_ALL_CHUC_VU, GET_CHUC_VU_BY_MA, GET_CHUC_VU_BY_TEN,
    GET_ALL_KHUYEN_MAI, GET_KHUYEN_MAI_BY_MA, ADD_KHUYEN_MAI, UPDATE_KHUYEN_MAI, DELETE_KHUYEN_MAI, SEARCH_KHUYEN_MAI, GET_NEXT_MA_KHUYEN_MAI,
    GET_ALL_THUE, GET_THUE_BY_MA,
    
    // Statistics
    GET_THONG_KE_THUOC_BAN_CHAY,
    GET_THONG_KE_TRONG_NGAY, GET_THONG_KE_TRONG_THANG, GET_THONG_KE_TRONG_NAM,
    GET_HOA_DON_CHI_TIET_TRONG_NGAY, GET_HOA_DON_CHI_TIET_TRONG_THANG, GET_HOA_DON_CHI_TIET_TRONG_NAM,
    GET_HOA_DON_CHI_TIET_TRONG_THANG_NAM, GET_TONG_KET_TRONG_NGAY, GET_TONG_KET_TRONG_THANG, GET_TONG_KET_TRONG_NAM,
    GET_THONG_KE_THEO_NGAY_TRONG_THANG, GET_THONG_KE_THEO_THANG_TRONG_NAM,
    ADD_CT_HOA_DON,
    CHECK_PHIEU_DOI_TRA_BY_HD
}
